# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Build specific stats linked to reviews

Resources:
    ProcessDuelsHighWinsFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: process-duels-high-wins.default
            Runtime: nodejs10.x
            CodeUri: ./dist/process-duels-high-wins
            MemorySize: 192
            Timeout: 40
            ReservedConcurrentExecutions: 1
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - SecretsManagerReadWrite
                - AmazonSESFullAccess
                - AmazonSQSFullAccess
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: process-duels-high-wins
            Events:
                SQSEvent:
                    Type: SQS
                    Properties:
                        Queue: arn:aws:sqs:us-west-2:478062583808:duels-high-wins-review-published-queue
